version: 1.0.{build}
image: Ubuntu2004
pull_requests:
    do_not_increment_build_number: true
branches:
    only:
        - main
environment:
    VERCEL_TOKEN:
        secure: InPNy6LbDQf4YYKZAVYpTbO0uRIKI6D3Dt+nHvOVvS8=
build: off
cache:
    - /var/lib/docker
    - /home/appveyor/.cache/yarn/v6
    - /home/appveyor/.nuget/packages
    - /home/appveyor/.npm
    - /home/appveyor/.yarn
    - /home/appveyor/.cargo
    - /home/appveyor/.udocker
install:
    - nvm use 14
    - python -V
    - export PATH="$(yarn global bin):$PATH"
    - yarn global add vercel
    - vercel -v
    - if [[ ! -z "${VERCEL_TOKEN}" ]]; then yarn global add vercel;fi
    - pushd website
    - yarn
    - popd
build_script:
    - pushd bench
    - sudo dotnet run -c Release -p tool -- --task build --force-pull-docker true
    - sudo dotnet run -c Release -p tool -- --task test
    - sudo dotnet run -c Release -p tool -- --task bench
    - popd
    - pushd website
    - yarn
    - yarn content
    - yarn generate
    - popd
artifacts:
    - path: bench/build/_results
      name: benchmark_results
    - path: website/dist
      name: website
on_success:
    - if [[ ! -z "${VERCEL_TOKEN}" ]]; then vercel website --prod -c -C -t $VERCEL_TOKEN;fi
