[package]
name = "_app"
version = "0.1.0"
authors = ["hanabi1224"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
typed-arena = "2"
rayon = "1"