name: bench
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  bench:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        # lang: [julia, javascript, typescript, go, csharp, java, kotlin]
        lang: [go]
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          echo 'Install'
      - name: Build
        run: |
          pushd bench
          dotnet run -c Release -p tool -- --task build --langs ${{ matrix.lang }} 
          popd
      - name: Test
        run: |
          pushd bench
          dotnet run -c Release -p tool -- --task test --langs ${{ matrix.lang }} 
          popd
      - name: Bench
        run: |
          pushd bench
          dotnet run -c Release -p tool -- --task bench --langs ${{ matrix.lang }} 
          popd
      - uses: actions/upload-artifact@v2
        with:
          name: log
          path: bench/build/_results/**/*.json
          if-no-files-found: error
  publish:
    needs: [bench]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.8
        with:
          # Artifact name
          name: log
          # Destination path
          path: bench/build/_results/
      - name: Install
        run: |
          ls -al bench/build/_results/
      - name: Site Update Content
        run: |
          pushd website
          yarn
          yarn content
      - name: Site Publish
        if: github.ref == 'refs/heads/main'
        env:
          VERCEL_PUBLISH_TOKEN: ${{ secrets.VERCEL_PUBLISH_TOKEN }}
        run: | 
          yarn global add vercel
          export PATH="$(yarn global bin):$PATH"
          vercel website  -f -c -C -t $VERCEL_PUBLISH_TOKEN
          
          
          
        
        
        
